### PR TITLE
Add support for Shell loops

### PR DESCRIPTION
**Pull request by me-and**
Treat Bash's if/for/while loops as parentheses.

### CODE REVIEW

**Comment by me-and** [comment]
...wait, no, that doesn't actually work. So much for a naive merge...

**Comment by me-and** [comment]
Okay, this is considerably more complex than I thought. Closing for now until I have this in a better shape.

**Comment by me-and** [comment]
Right, fine, the original pull request works just fine, I'd just made a mess of my `.vimrc` and was getting some apparently strange behaviour as a result.

This appears to work just fine, although it's using the old list-of-lists style to specify the regexes, rather than the relatively new `start`/`step`/`end` style, as I couldn't manage to get that to work, and I'm having trouble stepping through the Vimscript to work out what's going wrong.

I'm also seeing some odd colourings in my files unless I add `let g:sh_no_error = 1` to my `.vimrc`; without that it appears to think some things, like an "else" statement that starts on column 1, to be inexplicably errors and to highlight them as such.

**Comment by luochen1990** [comment]
Thanks for your contribution 👍 , I'm not sure if this complex configuration of parentheses is correct or not, but I will merge it, since it will not affect the main logic and I hope it is correct :)

**Pull request merged**
