### PR TITLE
Fix spell checking issues

### LINKED ISSUE #75: Spell-checking issues
I've been trying this plugin every once in a while for a few years now and I'm getting the same issue every time - spell checking is done for source code files. I'm seeing the issue in `Java`, `CoffeeScript`, `Handlebars templates` but not in `JavaScript` files for example. The "issue" is that words OUTSIDE of strings are highlighted as spelling mistakes - I want only strings to be checked. Is this possible? I've created a fork of `kien`'s Rainbow parentheses:

https://github.com/boris-petrov/rainbow_parentheses.vim

Which does exactly what I want with spellchecking. I would prefer to use this plugin instead but this issue is a blocker for me.

### PR DESCRIPTION
**Pull request by boris-petrov**
This fixes an issue which causes the spell checker to check words which are outside of quotes.

Fixes #75.

### CODE REVIEW

**Comment by alok** [comment]
@luochen1990 If it works, could this please be merged in?

**Comment by luochen1990** [comment]
`:h :syn-spell`,  if you add `@Spell` syntax rule, then for some filetypes which has no `@Spell` in the default syntax files, this will stop the default spell checking behavior.

**Comment by luochen1990** [comment]
So, this works for some cases , and some people who only works with specific file types, but it not works for everybody.

**Comment by alok** [comment]
Is there a way to modify it for the general case? I could perhaps pick up the PR.

**Comment by luochen1990** [comment]
none -> @Spell , https://github.com/luochen1990/rainbow/issues/22  ,  https://github.com/luochen1990/rainbow/commit/6bbf980377dcaccec946b5dd61b38aab2ef7e020
@Spell -> @NoSpell, https://github.com/luochen1990/rainbow/issues/24 ,  https://github.com/luochen1990/rainbow/commit/9a609c651b54a754183fe79fc302f41c521119e2
@NoSpell -> none , https://github.com/luochen1990/rainbow/issues/30 ,  https://github.com/luochen1990/rainbow/pull/59/files

**Comment by luochen1990** [comment]
@alok I think there is not an easy way to make it works for every case.  If we want to solve the spell checking problem, we have to deal with each file types one by one.

**Comment by luochen1990** [comment]
@alok this PR is closed, If there is some better idea, a new issue or PR is welcomed.

**Pull request closed without merging**
