### PR TITLE
Add support for dotted file type

### LINKED ISSUE #61: [req] Support combined filetypes
Combined filetypes are types that have one or more dots in them. `:h filetype` gives the following explanation:

> When a dot appears in the value then this separates two filetype names.  Example:
> 
> ```
> /* vim: set filetype=c.doxygen : */ ~
> ```
> 
> This will use the "c" filetype first, then the "doxygen" filetype.    This works both for filetype plugins and for syntax files.  More than one dot may appear.

I am using the HTML template-engine Jinja for websites and the filetype should be set to `html.jinja`, i.e. first apply settings by HTML, then the Jinja settings (current plugins don't do that, but I was considering doing my own). Here is the Jinja website with a code sample:

```
{% extends "layout.html" %}
{% block body %}
  <ul>
  {% for user in users %}
    <li><a href="{{ user.url }}">{{ user.username }}</a></li>
  {% endfor %}
  </ul>
{% endblock %}
```

http://jinja.pocoo.org/

However, when I set the file type to `html.jinja` I lose the rainbow feature. I have to add a new entry called `html.jinja` and then copy-paste the settings for HTML and Jinja into that new setting. What I would like would be if the two could somehow be combined automatically, first apply HTML and then Jinja. If there are no Jinja settings only apply the HTML ones, and if there are no HTML settings only apply the Jinja ones.

### PR DESCRIPTION
**Pull request by HiPhish**
Closes #61

### CODE REVIEW

**Comment by luochen1990** [comment]
Great job! this is a long code and takes me some time to review. I'll deal with it in a few days, please be patient :)

**Comment by HiPhish** [comment]
@luochen1990 There is a problem when the entry for a file type is not a dictionary, such as the default settings for CSS files:
```vim
'css': 0,
```
I have pushed a modified version of the commit now.

**Comment by HiPhish** [comment]
@luochen1990 Oops, another oversight. Should be working completely now.

**Comment by alok** [comment]
@luochen1990 If it works, could this please be merged in?

**Comment by alok** [comment]
Actually, line 194 should have a double equals since instead of a single equals.

**Comment by HiPhish** [comment]
> Actually, line 194 should have a double equals sign instead of a single equals.

I fixed it. Sorry for such a stupid mistake.

**Comment by luochen1990** [comment]
This feature is supported finally: https://github.com/luochen1990/rainbow/commit/3c3f4daed222f108b1b4d50bbf0d8abdf0b5f618

@HiPhish  Thanks for your smart idea and your contribution.

My implimentation is a little different than yours.  instead of fusion the configurations of different filetypes, it defines multiple groups of syntax rules independently.  Maybe it not works as good as your solutions sometimes (e.g. it will count parentheses levels separately), but IMO this strategy will be more general and will cause less issues.

**Comment by HiPhish** [comment]
Multiple syntax groups sounds fine; since there are multiple file types it's appropriate to count parentheses for each one individually. This issue can then be closed and my branch deleted.

**Pull request closed without merging**
