### PR TITLE
docs(readme): fix conflict with NERDTree

### PR DESCRIPTION
**Pull request by timsu92**
Sorry, I've forgot where did I found this, so I can't provide the link to the issue.

### CODE REVIEW

**Comment by timsu92** [comment]
I guess this is how it caused:
I have [nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin) installed, which shows the `[ ]` parentheses(bracket?) by default.
Originally, there's an option in that plugin to disable this. However, I have [vim-devicons](https://github.com/ryanoasis/vim-devicons) installed as well. As the readme indicates, I can't disable them.
And then, rainbow changes the color, so they aren't concealed.

**Comment by timsu92** [comment]
One of the file is `README.md` while the other one is suffixed with zh, which means Chinese. So I think people who open that file should be prepared to see the characters. 

BTW, contents in `README.md` and `README_zh.md` are inconsistent.

**Comment by luochen1990** [comment]
Oh, it's in `README_zh.md`, then it's not a problem.   

> BTW, contents in README.md and README_zh.md are inconsistent.

Yes, they are not expected to be consistent in each line, but their main part should be consistant. If not, please tell me.

**Comment by timsu92** [comment]
> their main part should be consistant. If not, please tell me.

Sorry but if you can read Chinese, it might be better to just see what's happening. I wanted to list all the differences. Sadly, however, there are just too many😢

Nevertheless, I guess current status is still controllable as many of the differences show that English version is better. 

Lastly, thanks for creating this! I really appreciate this work! It saves much of my time from making sure in which parenthesis I'm working!

**Pull request merged**
